#!/usr/bin/env python3
"""
gen_stdlib.py — Generate stdlib_sources.h

Exception / IEnumerable / etc. are no longer source-injected. They come from
core.xar via pipeline_load_sys_module + checker_declare_class_from_def.

SOURCE_MERGE_MODULES lists packages that still need full AST merge on import
(currently none — generics use ClassDef metadata).

Run from the XenoScript root:
    python3 source/stdlib/gen_stdlib.py
"""
import os, sys

root       = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
stdlib_dir = os.path.join(root, "stdlib")
out_path   = os.path.join(os.path.dirname(__file__), "stdlib_sources.h")

SOURCE_MERGE_MODULES = []

def read_xeno(path):
    with open(path, "r", encoding="utf-8") as f:
        src = f.read()
    if not src.endswith("\n"):
        src += "\n"
    return src

def escape_c_string(s):
    result = ""
    for line in s.split("\n"):
        escaped = line.replace("\\", "\\\\").replace('"', '\\"')
        result += f'    "{escaped}\\n"\n'
    return result

modules = {}
for name in SOURCE_MERGE_MODULES:
    mod_dir = os.path.join(stdlib_dir, name)
    if not os.path.isdir(mod_dir):
        print(f"Warning: stdlib/{name}/ not found, skipping", file=sys.stderr)
        continue
    src = ""
    for fname in sorted(os.listdir(mod_dir)):
        if fname.endswith(".xeno"):
            src += read_xeno(os.path.join(mod_dir, fname))
    modules[name] = src

with open(out_path, "w", encoding="utf-8") as out:
    out.write("/* AUTO-GENERATED by gen_stdlib.py -- do not edit by hand */\n")
    out.write("/* Stdlib reaches the checker via core.xar ClassDefs, not source inject. */\n")
    out.write("#pragma once\n\n#include <stddef.h>\n\n")
    out.write("typedef struct { const char *name; const char *source; } StdlibModule;\n\n")
    out.write("static const StdlibModule XENOSCRIPT_STDLIB[] = {\n")
    for name, src in modules.items():
        out.write(f'    {{ "{name}",\n')
        out.write(escape_c_string(src))
        out.write("    },\n")
    out.write("};\n\n")
    out.write(f"static const int XENOSCRIPT_STDLIB_COUNT = {len(modules)};\n")

print(f"Generated {out_path} ({len(modules)} source-merge module(s))")
