#!/usr/bin/env python3
"""
gen_stdlib.py — Generate stdlib_sources.h from stdlib/ directory tree.
Only modules needing source-merge at compile time are included (those with
generic classes). Pure .xar-staged modules (core, math) are excluded.

Run from the XenoScript root:
    python3 source/stdlib/gen_stdlib.py
"""
import os, sys

root       = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
stdlib_dir = os.path.join(root, "stdlib")
out_path   = os.path.join(os.path.dirname(__file__), "stdlib_sources.h")

# Only modules requiring source-merge (have generic classes needing AST nodes).
SOURCE_MERGE_MODULES = ["collections"]

modules = {}
for name in SOURCE_MERGE_MODULES:
    mod_dir = os.path.join(stdlib_dir, name)
    if not os.path.isdir(mod_dir):
        print(f"Warning: stdlib/{name}/ not found, skipping", file=sys.stderr)
        continue
    src = ""
    for fname in sorted(os.listdir(mod_dir)):
        if fname.endswith(".xeno"):
            with open(os.path.join(mod_dir, fname)) as f:
                src += f.read()
            if not src.endswith("\n"):
                src += "\n"
    modules[name] = src

with open(out_path, "w") as out:
    out.write("/* AUTO-GENERATED by gen_stdlib.py — do not edit by hand */\n")
    out.write("/* Source: stdlib modules requiring source-merge (generic classes) */\n")
    out.write("#pragma once\n\n#include <stddef.h>\n\n")
    out.write("typedef struct { const char *name; const char *source; } StdlibModule;\n\n")
    for name, src in modules.items():
        out.write(f"static const char xenostd_{name}_source[] =\n")
        for line in src.split("\n"):
            escaped = line.replace("\\", "\\\\").replace('"', '\\"')
            out.write(f'    "{escaped}\\n"\n')
        out.write(";\n\n")
    out.write("static const StdlibModule XENOSCRIPT_STDLIB[] = {\n")
    for name in modules:
        out.write(f'    {{ "{name}", xenostd_{name}_source }},\n')
    out.write("};\n\n")
    out.write(f"static const int XENOSCRIPT_STDLIB_COUNT = {len(modules)};\n")

print(f"Generated {out_path} ({len(modules)} module(s): {', '.join(modules)})")
