#!/usr/bin/env python3
"""
gen_stdlib_embed.py — Auto-generate stdlib embed headers from build/xar/

Scans build/xar/ for *.xar and *.xdoc and writes:
  includes/stdlib_xar.h
  includes/stdlib_xdoc.h
  build/xar/stdlib_embed.mk   (Make variables: lists of .o targets)

No module names are hard-coded. Add a directory under stdlib/, pack it to
build/xar/<name>.xar (+ .xdoc), re-run this script, rebuild.

Convention:
  stdlib/<name>/*.xeno  ->  build/xar/<name>.xar  +  build/xar/<name>.xdoc
  Linker symbols (ld -r -b binary):
    _binary_build_xar_<name>_xar_start / _end
    _binary_build_xar_<name>_xdoc_start / _end
  (slashes and dots in the path become underscores)

Usage (from repo root):
  python3 source/stdlib/gen_stdlib_embed.py
"""
from __future__ import annotations
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BUILD = ROOT / "build" / "xar"
INC = ROOT / "includes"
MK = BUILD / "stdlib_embed.mk"

# Modules always loaded at VM/LSP start (primitive helpers). Others are import-only.
# Override with env XENO_STDLIB_AUTO="core,foo" if needed.
AUTO = [x.strip() for x in os.environ.get("XENO_STDLIB_AUTO", "core").split(",") if x.strip()]


def binary_sym(path: Path, which: str) -> str:
    """ld -r -b binary symbol name for a path relative to ROOT."""
    # path like build/xar/core.xar -> build_xar_core_xar
    rel = path.resolve().relative_to(ROOT.resolve())
    base = str(rel).replace("/", "_").replace(".", "_").replace("-", "_")
    return f"_binary_{base}_{which}"


def write_xar_h(names: list[str]) -> None:
    auto = [n for n in names if n in AUTO]
    explicit = [n for n in names if n not in AUTO]
    lines = [
        "/* AUTO-GENERATED by gen_stdlib_embed.py — do not edit */",
        "#ifndef STDLIB_XAR_H",
        "#define STDLIB_XAR_H",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "typedef struct {",
        "    const char    *name;",
        "    const uint8_t *start;",
        "    const uint8_t *end;",
        "} StdlibXarEntry;",
        "",
    ]
    for n in names:
        p = BUILD / f"{n}.xar"
        s = binary_sym(p, "start")
        e = binary_sym(p, "end")
        lines.append(f'extern const uint8_t xar_{n}_start[] __asm("{s}");')
        lines.append(f'extern const uint8_t xar_{n}_end[]   __asm("{e}");')
        lines.append("")
    lines += [
        f"#define STDLIB_XAR_AUTO_COUNT {len(auto)}",
        f"#define STDLIB_XAR_EXPLICIT_COUNT {len(explicit)}",
        f"#define STDLIB_XAR_TOTAL_COUNT {len(names)}",
        "",
        "#ifndef XAR_BOOTSTRAP",
        "static const StdlibXarEntry STDLIB_XAR_TABLE[] = {",
    ]
    for n in auto:
        lines.append(f'    {{ "{n}", xar_{n}_start, xar_{n}_end }},')
    for n in explicit:
        lines.append(f'    {{ "{n}", xar_{n}_start, xar_{n}_end }},')
    if not names:
        lines.append("    { 0, 0, 0 },")
    lines += [
        "};",
        "#else",
        "#undef  STDLIB_XAR_TOTAL_COUNT",
        "#define STDLIB_XAR_TOTAL_COUNT 0",
        "static const StdlibXarEntry STDLIB_XAR_TABLE[] = {{0}};",
        "#endif",
        "",
        "#endif /* STDLIB_XAR_H */",
        "",
    ]
    INC.mkdir(parents=True, exist_ok=True)
    (INC / "stdlib_xar.h").write_text("\n".join(lines))


def write_xdoc_h(names: list[str]) -> None:
    lines = [
        "/* AUTO-GENERATED by gen_stdlib_embed.py — do not edit */",
        "#ifndef STDLIB_XDOC_H",
        "#define STDLIB_XDOC_H",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "typedef struct {",
        "    const char    *name;",
        "    const uint8_t *start;",
        "    const uint8_t *end;",
        "} StdlibXdocEntry;",
        "",
    ]
    for n in names:
        p = BUILD / f"{n}.xdoc"
        s = binary_sym(p, "start")
        e = binary_sym(p, "end")
        lines.append(f'extern const uint8_t xdoc_{n}_start[] __asm("{s}");')
        lines.append(f'extern const uint8_t xdoc_{n}_end[]   __asm("{e}");')
        lines.append("")
    lines += [
        f"#define STDLIB_XDOC_COUNT {len(names)}",
        "",
        "#ifndef XAR_BOOTSTRAP",
        "static const StdlibXdocEntry STDLIB_XDOC_TABLE[] = {",
    ]
    for n in names:
        lines.append(f'    {{ "{n}", xdoc_{n}_start, xdoc_{n}_end }},')
    if not names:
        lines.append("    { 0, 0, 0 },")
    lines += [
        "};",
        "#else",
        "#undef  STDLIB_XDOC_COUNT",
        "#define STDLIB_XDOC_COUNT 0",
        "static const StdlibXdocEntry STDLIB_XDOC_TABLE[] = {{0}};",
        "#endif",
        "",
        "#endif /* STDLIB_XDOC_H */",
        "",
    ]
    (INC / "stdlib_xdoc.h").write_text("\n".join(lines))


def write_mk(xar_names: list[str], xdoc_names: list[str]) -> None:
    BUILD.mkdir(parents=True, exist_ok=True)
    lines = [
        "# AUTO-GENERATED by gen_stdlib_embed.py — do not edit",
        "# Included from the top-level Makefile.",
        "",
        "STDLIB_MODULES := " + " ".join(xar_names),
        "",
        "STDLIB_OBJS_LINUX := " + " ".join(f"$(BUILD)/{n}.xar.linux.o" for n in xar_names),
        "STDLIB_OBJS_WIN64 := " + " ".join(f"$(BUILD)/{n}.xar.win64.o" for n in xar_names),
        "",
        "STDLIB_XDOC_OBJS_LINUX := " + " ".join(f"$(BUILD)/{n}.xdoc.linux.o" for n in xdoc_names),
        "STDLIB_XDOC_OBJS_WIN64 := " + " ".join(f"$(BUILD)/{n}.xdoc.win64.o" for n in xdoc_names),
        "",
    ]
    MK.write_text("\n".join(lines))


def main() -> int:
    if not BUILD.is_dir():
        print(f"gen_stdlib_embed: {BUILD} missing — pack stdlib first", file=sys.stderr)
        # Still write empty tables so bootstrap can compile
        write_xar_h([])
        write_xdoc_h([])
        write_mk([], [])
        return 0

    xar_names = sorted(p.stem for p in BUILD.glob("*.xar"))
    xdoc_names = sorted(p.stem for p in BUILD.glob("*.xdoc"))
    # Prefer modules that have both when listing; keep xar-only and xdoc-only
    write_xar_h(xar_names)
    write_xdoc_h(xdoc_names)
    write_mk(xar_names, xdoc_names)
    print(f"gen_stdlib_embed: xar={xar_names} xdoc={xdoc_names}")
    print(f"  wrote {INC / 'stdlib_xar.h'}")
    print(f"  wrote {INC / 'stdlib_xdoc.h'}")
    print(f"  wrote {MK}")
    return 0


if __name__ == "__main__":
    sys.exit(main())