#!/usr/bin/env python3
"""
gen_stdlib.py — Generate stdlib_sources.h from stdlib/ directory tree.
Only modules needing source-merge at compile time are included (those with
generic classes). Pure .xar-staged modules (core, math) are excluded.

Two special injection strings (xenostd_exception_source,
xenostd_enumerable_source) are hand-maintained at the bottom of this file
and written verbatim — they contain only the minimal interface/base-class
declarations needed by the checker, NOT the full stdlib implementation
(which lives in core.xar).

Run from the XenoScript root:
    python3 source/stdlib/gen_stdlib.py
"""
import os, sys

root       = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
stdlib_dir = os.path.join(root, "stdlib")
out_path   = os.path.join(os.path.dirname(__file__), "stdlib_sources.h")

# Modules requiring full source-merge (have generic classes needing AST nodes).
SOURCE_MERGE_MODULES = []

modules = {}
for name in SOURCE_MERGE_MODULES:
    mod_dir = os.path.join(stdlib_dir, name)
    if not os.path.isdir(mod_dir):
        print(f"Warning: stdlib/{name}/ not found, skipping", file=sys.stderr)
        continue
    src = ""
    for fname in sorted(os.listdir(mod_dir)):
        if fname.endswith(".xeno"):
            with open(os.path.join(mod_dir, fname)) as f:
                src += f.read()
            if not src.endswith("\n"):
                src += "\n"
    modules[name] = src

# Minimal checker-injection stubs (NOT the full implementation — that is in core.xar).
# Only the interface/base-class signatures the checker needs to type-check user code.
EXCEPTION_STUB = """\
class Exception {
    public:
        string message;
        Exception(string message) { this.message = message; }
        function toString(): string { return this.message; }
}
"""

ENUMERABLE_STUB = """\
interface IEnumerator<T> {
    function moveNext(): bool;
    function current(): T;
}
interface IEnumerable<T> {
    function getEnumerator(): IEnumerator<T>;
}
"""

def escape_c_string(s):
    lines = s.split("\n")
    result = ""
    for line in lines:
        escaped = line.replace("\\", "\\\\").replace('"', '\\"')
        result += f'    "{escaped}\\n"\n'
    return result

with open(out_path, "w") as out:
    out.write("/* AUTO-GENERATED by gen_stdlib.py -- do not edit by hand */\n")
    out.write("/* Source: stdlib modules requiring source-merge (generic classes) */\n")
    out.write("#pragma once\n\n#include <stddef.h>\n\n")
    out.write("typedef struct { const char *name; const char *source; } StdlibModule;\n\n")

    # Full source-merge modules (generics)
    for name, src in modules.items():
        out.write(f"static const char xenostd_{name}_source[] =\n")
        out.write(escape_c_string(src))
        out.write(";\n\n")

    # Minimal checker-injection stubs
    out.write("/* Minimal stubs injected into every compilation for checker visibility.\n")
    out.write(" * Full implementations live in core.xar. */\n")
    out.write("static const char xenostd_exception_source[] =\n")
    out.write(escape_c_string(EXCEPTION_STUB))
    out.write(";\n\n")
    out.write("static const char xenostd_enumerable_source[] =\n")
    out.write(escape_c_string(ENUMERABLE_STUB))
    out.write(";\n\n")

    out.write("static const StdlibModule XENOSCRIPT_STDLIB[] = {\n")
    for name in modules:
        out.write(f'    {{ "{name}", xenostd_{name}_source }},\n')
    out.write("};\n\n")
    out.write(f"static const int XENOSCRIPT_STDLIB_COUNT = {len(modules)};\n")

print(f"Generated {out_path} ({len(modules)} source-merge module(s): {', '.join(modules)}; + 2 stub strings)")
