/* AUTO-GENERATED by gen_stdlib.py -- do not edit by hand */
/* Source: stdlib modules requiring source-merge (generic classes) */
#pragma once

#include <stddef.h>

typedef struct { const char *name; const char *source; } StdlibModule;

/* Minimal stubs injected into every compilation for checker visibility.
 * Full implementations live in core.xar. */
static const char xenostd_exception_source[] =
    "class Exception {\n"
    "    public:\n"
    "        string message;\n"
    "        Exception(string message) { this.message = message; }\n"
    "        function toString(): string { return this.message; }\n"
    "}\n"
    "\n"
;

static const char xenostd_enumerable_source[] =
    "interface IEnumerator<T> {\n"
    "    function moveNext(): bool;\n"
    "    function current(): T;\n"
    "}\n"
    "interface IEnumerable<T> {\n"
    "    function getEnumerator(): IEnumerator<T>;\n"
    "}\n"
    "\n"
;

static const StdlibModule XENOSCRIPT_STDLIB[] = {
};

static const int XENOSCRIPT_STDLIB_COUNT = 0;
