/* AUTO-GENERATED by gen_stdlib.py -- do not edit by hand */
/* Stdlib reaches the checker via core.xar ClassDefs, not source inject. */
#pragma once

#include <stddef.h>

typedef struct { const char *name; const char *source; } StdlibModule;

static const StdlibModule XENOSCRIPT_STDLIB[] = {
};

static const int XENOSCRIPT_STDLIB_COUNT = 0;
