# ==========================================================
# XenoScript Makefile
# Runs under WSL — targets Linux and Win64 via mingw
#
# Targets:
#   all              Build xenoc + xenovm + xar + xenolsp (linux+win64)
#   linux            Linux binaries only
#   win64            Win64 binaries only
#   stdlib           Rebuild stdlib packs, embeds (bootstrap + pack)
#   xeno_tests       Run language tests
#   xeno_speed_test  Run speed test
#   xeno_tests_asan  Tests under ASan + UBSan (Linux)
#   clean            Remove build/ and bin/
#
# Normal `make` / `make linux` only recompiles C sources and relinks.
# Stdlib packing (xar-bootstrap) runs ONLY when:
#   - you run `make stdlib`, or
#   - an embedded .o is missing and its .xar must be produced from sources
# ==========================================================

CC_LINUX  := /usr/bin/gcc
CC_WIN64  := /usr/bin/x86_64-w64-mingw32-gcc
LD_WIN64  := /usr/bin/x86_64-w64-mingw32-ld

CFLAGS    := -std=c17 -Wall -Wextra -Iincludes -O2 -g \
             -Wno-array-bounds \
             -Wno-maybe-uninitialized \
             -Wno-stringop-overflow
LDFLAGS   := -lm

BUILD     := build/xar
BIN       := bin

# ==========================================================
# Sources
# ==========================================================

CORE_SRCS := \
    source/core/lexer.c    \
    source/core/ast.c      \
    source/core/parser.c   \
    source/core/checker.c  \
    source/core/bytecode.c

COMPILER_SRCS := \
    source/compiler/compiler.c \
    source/compiler/xbc.c      \
    source/compiler/module_strip_stdlib.c \
    source/compiler/xdoc.c

# Bootstrap packer: no module_strip_stdlib (no embedded stdlib yet)
COMPILER_SRCS_BOOTSTRAP := \
    source/compiler/compiler.c \
    source/compiler/xbc.c      \
    source/compiler/xdoc.c

VM_SRCS  := source/vm/vm.c source/vm/platform_time.c
XAR_SRCS := source/xar/xar.c source/xar/toml.c

STDLIB_DECLARE   := source/stdlib/stdlib_declare.c
STDLIB_REGISTER  := source/stdlib/stdlib_register.c
STDLIB_SOURCES_H := source/stdlib/stdlib_sources.h

XENOC_SRCS  := $(CORE_SRCS) $(COMPILER_SRCS) $(XAR_SRCS) $(STDLIB_DECLARE) \
               source/compiler/xenoc_main.c
XENOVM_SRCS := $(CORE_SRCS) $(COMPILER_SRCS) $(VM_SRCS) $(XAR_SRCS) $(STDLIB_REGISTER) \
               source/vm/xenovm_main.c
XAR_TOOL_SRCS := $(CORE_SRCS) $(COMPILER_SRCS) $(XAR_SRCS) $(STDLIB_DECLARE) \
                 source/xar/xar_main.c
XAR_BOOTSTRAP_SRCS := $(CORE_SRCS) $(COMPILER_SRCS_BOOTSTRAP) $(XAR_SRCS) $(STDLIB_DECLARE) \
                      source/xar/xar_main.c

LSP_SRCS := $(CORE_SRCS) $(COMPILER_SRCS) $(XAR_SRCS) $(STDLIB_DECLARE) \
    source/lsp/jsonrpc.c \
    source/lsp/json.c \
    source/lsp/stub_gen.c \
    source/lsp/doc_store.c \
    source/lsp/lsp_main.c

# ==========================================================
# Stdlib discovery — every stdlib/<name>/ directory becomes a module
# ==========================================================

STDLIB_DIRS  := $(wildcard stdlib/*/)
STDLIB_NAMES := $(notdir $(STDLIB_DIRS:/=))
STDLIB_XARS  := $(addprefix $(BUILD)/,$(addsuffix .xar,$(STDLIB_NAMES)))

# Object lists generated by gen_stdlib_embed.py (after packs exist)
-include $(BUILD)/stdlib_embed.mk

# Fallback empty lists until first `make stdlib`
STDLIB_OBJS_LINUX      ?=
STDLIB_OBJS_WIN64      ?=
STDLIB_XDOC_OBJS_LINUX ?=
STDLIB_XDOC_OBJS_WIN64 ?=

# ==========================================================
# Default
# ==========================================================

.PHONY: all linux win64
all: linux win64

linux: $(BIN)/xenoc $(BIN)/xenovm $(BIN)/xar $(BIN)/xenolsp
win64: $(BIN)/xenoc.exe $(BIN)/xenovm.exe $(BIN)/xar.exe $(BIN)/xenolsp.exe

# ==========================================================
# Bootstrap xar — ONLY used to pack stdlib (not linked into tools)
# ==========================================================

$(BIN)/xar-bootstrap: $(XAR_BOOTSTRAP_SRCS) | $(BIN)
	@printf "🔧 Building xar bootstrap...\n"
	@$(CC_LINUX) $(CFLAGS) -DXAR_BOOTSTRAP $(XAR_BOOTSTRAP_SRCS) -o $@ $(LDFLAGS)

# ==========================================================
# Pack stdlib/<name>/ → build/xar/<name>.xar (+ sibling .xdoc)
# Bootstrap is order-only: updating the packer does not force re-pack.
# ==========================================================

$(BUILD)/%.xar: stdlib/%/*.xeno | $(BIN)/xar-bootstrap $(BUILD)
	@printf "📦 Packing stdlib/$* → $@\n"
	@$(BIN)/xar-bootstrap pack stdlib/$*/ -o $@ -n $* -v 1.0.0

# ==========================================================
# Embed generation + phony stdlib target
# ==========================================================

$(BUILD)/stdlib_embed.mk: $(STDLIB_XARS) | $(BUILD)
	@printf "🐍 Generating stdlib embed headers...\n"
	@python3 source/stdlib/gen_stdlib_embed.py

.PHONY: stdlib
stdlib: $(BUILD)/stdlib_embed.mk
	@$(MAKE) --no-print-directory $(STDLIB_OBJS_LINUX) $(STDLIB_OBJS_WIN64) \
	         $(STDLIB_XDOC_OBJS_LINUX) $(STDLIB_XDOC_OBJS_WIN64)
	@printf "✅ Stdlib rebuilt.\n"

# ==========================================================
# Embed binary blobs (pattern rules)
# ==========================================================

$(BUILD)/%.xar.linux.o: $(BUILD)/%.xar
	@printf "📦 Embedding $< (linux)\n"
	@ld -r -b binary $< -o $@.tmp
	@objcopy --add-section .note.GNU-stack=/dev/null $@.tmp $@
	@rm -f $@.tmp

$(BUILD)/%.xar.win64.o: $(BUILD)/%.xar
	@printf "📦 Embedding $< (win64)\n"
	@$(LD_WIN64) -r -b binary $< -o $@

$(BUILD)/%.xdoc.linux.o: $(BUILD)/%.xdoc
	@printf "📄 Embedding $< (linux)\n"
	@ld -r -b binary $< -o $@.tmp
	@objcopy --add-section .note.GNU-stack=/dev/null $@.tmp $@
	@rm -f $@.tmp

$(BUILD)/%.xdoc.win64.o: $(BUILD)/%.xdoc
	@printf "📄 Embedding $< (win64)\n"
	@$(LD_WIN64) -r -b binary $< -o $@

# ==========================================================
# stdlib_sources.h (optional source-merge stubs)
# ==========================================================

$(STDLIB_SOURCES_H): $(wildcard stdlib/*/*.xeno)
	@printf "🐍 Regenerating stdlib_sources.h...\n"
	@python3 source/stdlib/gen_stdlib.py

# ==========================================================
# Guard: binaries need embeds. If missing, point at `make stdlib`.
# ==========================================================

define NEED_STDLIB
	@if [ -z "$(STDLIB_OBJS_LINUX)" ] || [ ! -f "$(BUILD)/stdlib_embed.mk" ]; then \
		printf "❌ Stdlib embeds missing. Run:  make stdlib\n"; \
		exit 1; \
	fi
endef

# ==========================================================
# Linux binaries — depend on embed .o lists, NOT on pack/bootstrap
# ==========================================================

$(BIN)/xenoc: $(XENOC_SRCS) $(STDLIB_OBJS_LINUX) $(STDLIB_SOURCES_H) | $(BIN)
	$(NEED_STDLIB)
	@printf "🐧 Linking xenoc (linux)...\n"
	@$(CC_LINUX) $(CFLAGS) $(XENOC_SRCS) $(STDLIB_OBJS_LINUX) -o $@ $(LDFLAGS)

$(BIN)/xenovm: $(XENOVM_SRCS) $(STDLIB_OBJS_LINUX) | $(BIN)
	$(NEED_STDLIB)
	@printf "🐧 Linking xenovm (linux)...\n"
	@$(CC_LINUX) $(CFLAGS) $(XENOVM_SRCS) $(STDLIB_OBJS_LINUX) -o $@ $(LDFLAGS)

$(BIN)/xar: $(XAR_TOOL_SRCS) $(STDLIB_OBJS_LINUX) $(STDLIB_SOURCES_H) | $(BIN)
	$(NEED_STDLIB)
	@printf "🔧 Building xar tool...\n"
	@$(CC_LINUX) $(CFLAGS) $(XAR_TOOL_SRCS) $(STDLIB_OBJS_LINUX) -o $@ $(LDFLAGS)

$(BIN)/xenolsp: $(LSP_SRCS) $(STDLIB_OBJS_LINUX) $(STDLIB_XDOC_OBJS_LINUX) \
                $(STDLIB_SOURCES_H) | $(BIN)
	$(NEED_STDLIB)
	@printf "🐧 Linking xenolsp (linux)...\n"
	@$(CC_LINUX) $(CFLAGS) $(LSP_SRCS) $(STDLIB_OBJS_LINUX) $(STDLIB_XDOC_OBJS_LINUX) -o $@ $(LDFLAGS)

# ==========================================================
# Win64 binaries
# ==========================================================

$(BIN)/xenoc.exe: $(XENOC_SRCS) $(STDLIB_OBJS_WIN64) $(STDLIB_SOURCES_H) | $(BIN)
	$(NEED_STDLIB)
	@printf "🪟 Linking xenoc.exe (win64)...\n"
	@$(CC_WIN64) $(CFLAGS) $(XENOC_SRCS) $(STDLIB_OBJS_WIN64) -o $@ $(LDFLAGS)

$(BIN)/xar.exe: $(XAR_TOOL_SRCS) $(STDLIB_OBJS_WIN64) $(STDLIB_SOURCES_H) | $(BIN)
	$(NEED_STDLIB)
	@printf "🪟 Building xar.exe (win64)...\n"
	@$(CC_WIN64) $(CFLAGS) $(XAR_TOOL_SRCS) $(STDLIB_OBJS_WIN64) -o $@ $(LDFLAGS)

$(BIN)/xenolsp.exe: $(LSP_SRCS) $(STDLIB_OBJS_WIN64) $(STDLIB_XDOC_OBJS_WIN64) \
                    $(STDLIB_SOURCES_H) | $(BIN)
	$(NEED_STDLIB)
	@printf "🪟 Linking xenolsp.exe (win64)...\n"
	@$(CC_WIN64) $(CFLAGS) $(LSP_SRCS) $(STDLIB_OBJS_WIN64) $(STDLIB_XDOC_OBJS_WIN64) -o $@ $(LDFLAGS)

$(BIN)/xenovm.exe: $(XENOVM_SRCS) $(STDLIB_OBJS_WIN64) | $(BIN)
	$(NEED_STDLIB)
	@printf "🪟 Linking xenovm.exe (win64)...\n"
	@$(CC_WIN64) $(CFLAGS) $(XENOVM_SRCS) $(STDLIB_OBJS_WIN64) -o $@ $(LDFLAGS)

# ==========================================================
# Sanitizer build (Linux) — ASan + UBSan
# ==========================================================

SAN_FLAGS := -std=c17 -Wall -Wextra -Iincludes -O1 -g -fno-omit-frame-pointer \
             -fsanitize=address,undefined -fno-sanitize-recover=undefined

$(BIN)/xenoc-asan: $(XENOC_SRCS) $(STDLIB_OBJS_LINUX) $(STDLIB_SOURCES_H) | $(BIN)
	$(NEED_STDLIB)
	@printf "🧪 Linking xenoc-asan...\n"
	@$(CC_LINUX) $(SAN_FLAGS) $(XENOC_SRCS) $(STDLIB_OBJS_LINUX) -o $@ $(LDFLAGS)

$(BIN)/xenovm-asan: $(XENOVM_SRCS) $(STDLIB_OBJS_LINUX) | $(BIN)
	$(NEED_STDLIB)
	@printf "🧪 Linking xenovm-asan...\n"
	@$(CC_LINUX) $(SAN_FLAGS) $(XENOVM_SRCS) $(STDLIB_OBJS_LINUX) -o $@ $(LDFLAGS)

.PHONY: xeno_tests_asan
xeno_tests_asan: $(BIN)/xenoc-asan $(BIN)/xenovm-asan
	@rm -rf asan_logs && mkdir -p asan_logs
	@ASAN_OPTIONS=detect_leaks=1:log_path=asan_logs/log \
	 UBSAN_OPTIONS=print_stacktrace=1:log_path=asan_logs/ubsan \
	 python3 source/tools/run_tests.py $(BIN)/xenoc-asan $(BIN)/xenovm-asan test/ || true
	@printf "\nNon-empty sanitizer logs:\n"; find asan_logs -type f -size +0 | sort || true

# ==========================================================
# Directories
# ==========================================================

$(BUILD) $(BIN):
	@mkdir -p $@

# ==========================================================
# Tests
# ==========================================================

.PHONY: xeno_tests
xeno_tests: $(BIN)/xenoc $(BIN)/xenovm
	@python3 source/tools/run_tests.py $(BIN)/xenoc $(BIN)/xenovm test/

.PHONY: xeno_speed_test
xeno_speed_test: $(BIN)/xenoc $(BIN)/xenovm
	@python3 source/tools/run_speed_test.py $(BIN)/xenoc $(BIN)/xenovm test/01_primitives.xeno 1000

# ==========================================================
# Clean — tolerate locked Windows binaries (WSL + VS Code LSP)
# ==========================================================

.PHONY: clean
clean:
	@rm -rf build 2>/dev/null || true
	@rm -rf bin 2>/dev/null || true
	@printf "🧽 Cleaned (locked files under bin/ may remain if the LSP holds them).\n"