/*
 * stdlib_xar.h — Embedded XenoScript Standard Library Archives
 *
 * AUTO-GENERATED by the build system — do not edit by hand.
 * Regenerate by running: make stdlib_embed
 *
 * Each stdlib directory is packed into a .xar and embedded via objcopy
 * into the compiler and VM binaries. The symbols below are the linker
 * symbols created by objcopy's --input-target binary transform.
 *
 * The __asm() attribute provides the exact linker symbol name, which is
 * required for mingw cross-compilation where an extra leading underscore
 * is added — __asm("_binary_...") works for both native Linux and mingw.
 *
 * Usage:
 *   XarArchive ar;
 *   size_t size = xar_core_end - xar_core_start;
 *   xar_read_mem(&ar, xar_core_start, size);
 */

#ifndef STDLIB_XAR_H
#define STDLIB_XAR_H

#include <stdint.h>
#include <stddef.h>

/* ── core.xar (int, float, bool, string primitive extensions) ─────────── */
extern const uint8_t xar_core_start[] __asm("_binary_build_xar_core_xar_start");
extern const uint8_t xar_core_end[]   __asm("_binary_build_xar_core_xar_end");

/* ── math.xar (C-backed mathematical functions) ──────────────────────── */
extern const uint8_t xar_math_start[] __asm("_binary_build_xar_math_xar_start");
extern const uint8_t xar_math_end[]   __asm("_binary_build_xar_math_xar_end");

/* ── collections.xar (List<T>, Stack<T>, Queue<T>) ───────────────────── */
extern const uint8_t xar_collections_start[] __asm("_binary_build_xar_collections_xar_start");
extern const uint8_t xar_collections_end[]   __asm("_binary_build_xar_collections_xar_end");

/* ── Stdlib table — all embedded archives ────────────────────────────── */

typedef struct {
    const char    *name;          /* Import name: "core", "math", "collections" */
    const uint8_t *start;         /* Pointer to embedded .xar data              */
    const uint8_t *end;           /* One past the last byte                     */
} StdlibXarEntry;

/* Modules that are ALWAYS loaded (primitive extension support). */
#define STDLIB_XAR_AUTO_COUNT 1
/* Modules loaded on explicit import <name>. */
#define STDLIB_XAR_EXPLICIT_COUNT 2
#define STDLIB_XAR_TOTAL_COUNT (STDLIB_XAR_AUTO_COUNT + STDLIB_XAR_EXPLICIT_COUNT)

static const StdlibXarEntry STDLIB_XAR_TABLE[] = {
    /* Auto-loaded (index 0..STDLIB_XAR_AUTO_COUNT-1) */
    { "core",        xar_core_start,        xar_core_end        },
    /* Explicit import <name> */
    { "math",        xar_math_start,        xar_math_end        },
    { "collections", xar_collections_start, xar_collections_end },
};

#endif /* STDLIB_XAR_H */
