/* AUTO-GENERATED by gen_stdlib_embed.py — do not edit */
#ifndef STDLIB_XDBG_H
#define STDLIB_XDBG_H

#include <stdint.h>
#include <stddef.h>

typedef struct {
    const char    *name;
    const uint8_t *start;
    const uint8_t *end;
} StdlibXdbgEntry;

extern const uint8_t xdbg_collections_start[] __asm("_binary_build_xar_collections_xdbg_start");
extern const uint8_t xdbg_collections_end[]   __asm("_binary_build_xar_collections_xdbg_end");

extern const uint8_t xdbg_core_start[] __asm("_binary_build_xar_core_xdbg_start");
extern const uint8_t xdbg_core_end[]   __asm("_binary_build_xar_core_xdbg_end");

extern const uint8_t xdbg_math_start[] __asm("_binary_build_xar_math_xdbg_start");
extern const uint8_t xdbg_math_end[]   __asm("_binary_build_xar_math_xdbg_end");

#define STDLIB_XDBG_COUNT 3

#ifndef XAR_BOOTSTRAP
static const StdlibXdbgEntry STDLIB_XDBG_TABLE[] = {
    { "collections", xdbg_collections_start, xdbg_collections_end },
    { "core", xdbg_core_start, xdbg_core_end },
    { "math", xdbg_math_start, xdbg_math_end },
};
#else
#undef  STDLIB_XDBG_COUNT
#define STDLIB_XDBG_COUNT 0
static const StdlibXdbgEntry STDLIB_XDBG_TABLE[] = {{0}};
#endif

#endif /* STDLIB_XDBG_H */
