/* AUTO-GENERATED by gen_stdlib_embed.py — do not edit */
#ifndef STDLIB_XAR_H
#define STDLIB_XAR_H

#include <stdint.h>
#include <stddef.h>

typedef struct {
    const char    *name;
    const uint8_t *start;
    const uint8_t *end;
} StdlibXarEntry;

extern const uint8_t xar_collections_start[] __asm("_binary_build_xar_collections_xar_start");
extern const uint8_t xar_collections_end[]   __asm("_binary_build_xar_collections_xar_end");

extern const uint8_t xar_core_start[] __asm("_binary_build_xar_core_xar_start");
extern const uint8_t xar_core_end[]   __asm("_binary_build_xar_core_xar_end");

extern const uint8_t xar_math_start[] __asm("_binary_build_xar_math_xar_start");
extern const uint8_t xar_math_end[]   __asm("_binary_build_xar_math_xar_end");

#define STDLIB_XAR_AUTO_COUNT 1
#define STDLIB_XAR_EXPLICIT_COUNT 2
#define STDLIB_XAR_TOTAL_COUNT 3

#ifndef XAR_BOOTSTRAP
static const StdlibXarEntry STDLIB_XAR_TABLE[] = {
    { "core", xar_core_start, xar_core_end },
    { "collections", xar_collections_start, xar_collections_end },
    { "math", xar_math_start, xar_math_end },
};
#else
#undef  STDLIB_XAR_TOTAL_COUNT
#define STDLIB_XAR_TOTAL_COUNT 0
static const StdlibXarEntry STDLIB_XAR_TABLE[] = {{0}};
#endif

#endif /* STDLIB_XAR_H */
