/* AUTO-GENERATED by gen_stdlib_embed.py — do not edit */
#ifndef STDLIB_XDOC_H
#define STDLIB_XDOC_H

#include <stdint.h>
#include <stddef.h>

typedef struct {
    const char    *name;
    const uint8_t *start;
    const uint8_t *end;
} StdlibXdocEntry;

extern const uint8_t xdoc_collections_start[] __asm("_binary_build_xar_collections_xdoc_start");
extern const uint8_t xdoc_collections_end[]   __asm("_binary_build_xar_collections_xdoc_end");

extern const uint8_t xdoc_core_start[] __asm("_binary_build_xar_core_xdoc_start");
extern const uint8_t xdoc_core_end[]   __asm("_binary_build_xar_core_xdoc_end");

extern const uint8_t xdoc_math_start[] __asm("_binary_build_xar_math_xdoc_start");
extern const uint8_t xdoc_math_end[]   __asm("_binary_build_xar_math_xdoc_end");

#define STDLIB_XDOC_COUNT 3

#ifndef XAR_BOOTSTRAP
static const StdlibXdocEntry STDLIB_XDOC_TABLE[] = {
    { "collections", xdoc_collections_start, xdoc_collections_end },
    { "core", xdoc_core_start, xdoc_core_end },
    { "math", xdoc_math_start, xdoc_math_end },
};
#else
#undef  STDLIB_XDOC_COUNT
#define STDLIB_XDOC_COUNT 0
static const StdlibXdocEntry STDLIB_XDOC_TABLE[] = {{0}};
#endif

#endif /* STDLIB_XDOC_H */
